CREATE VIEW tdda.accounts_enhanced
AS SELECT
   *,
   HOME_TEL IS NULL AND MOBILE_TEL IS NULL as NO_TEL,
   CLOSE_DATE IS NOT NULL AND (CLOSE_DATE < OPEN_DATE) AS CLOSE_BEFORE_OPEN,
   EXTRACT(EPOCH FROM (OPEN_DATE - now()::TIMESTAMP)) AS OPEN_SECS_IN_FUTURE,
   EXTRACT(EPOCH FROM (OPEN_DATE - now()::TIMESTAMP)) AS CLOSE_SECS_IN_FUTURE
FROM tdda.accounts;
