"""
test_metagentest.py: Automatically generated test code from tdda gentest.

Generation command:

tdda gentest "tdda gentest 'sh count-occurrences.sh Alice alice.txt' testalice1.py" 'test_metagentest.py' '.'

Then modified by hand slightly to fix the exclusion patterns for
the output from the inner gentest command, which the outer gentest
currently gets wrong.
"""

import os
import sys
import tempfile

from tdda.referencetest import ReferenceTestCase
from tdda.referencetest.gentest import exec_command


class Test_METAGENTEST(ReferenceTestCase):
    command = "tdda gentest 'sh count-occurrences.sh Alice alice.txt' testalice1.py"
    cwd = os.path.abspath(os.path.dirname(__file__))
    refdir = os.path.join(cwd, 'ref', 'metagentest')

    generated_files = [
        os.path.join(refdir, 'alice1/STDERR'),
    os.path.join(refdir, 'alice1/STDOUT'),
    os.path.join(cwd, 'testalice1.py')
    ]
    @classmethod
    def setUpClass(cls):
        for path in cls.generated_files:
            if os.path.exists(path):
                os.unlink(path)
        (cls.output,
         cls.error,
         cls.exception,
         cls.exit_code,
         cls.duration) = exec_command(cls.command, cls.cwd)

    def test_no_exception(self):
        self.assertIsNone(self.exception)

    def test_exit_code(self):
        self.assertEqual(self.exit_code, 0)

    def test_stdout(self):
        # STDOUT from "gentest 'sh countoccurrences ...' ..."
        patterns = [
            '^Command execution took: [0-9].[0-9]{3}s$',
            '^Directory to run in:    [.*]/c9/metagentest$',
            'Test script generated:   [.*]/c9/metagentest/testalice1.py$',
        ]
        removals = [
        ]
        self.assertStringCorrect(self.output,
                                 os.path.join(self.refdir, 'STDOUT'),
                                 ignore_patterns=patterns)

    def test_stderr(self):
        # STDERR from "gentest 'sh countoccurrences ...' ..."
        # (Empty)
        self.assertStringCorrect(self.error,
                                 os.path.join(self.refdir, 'STDERR'))

    def test_STDERR(self):
        # Test for error output from 'sh countoccurrences ...' iself (inner)
        # (Also, in fact, empty)
        self.assertBinaryFileCorrect(os.path.join(self.cwd,
                                                  'ref/alice1/STDERR'),
                                     os.path.join(self.refdir, 'STDERR1'))

    def test_STDOUT(self):
        # Test for output from 'sh countoccurrences ...' iself (inner)
        self.assertTextFileCorrect(os.path.join(self.cwd, 'ref/alice1/STDOUT'),
                                   os.path.join(self.refdir, 'STDOUT1'),
                                   encoding='ascii')

    def test_testalice1_py(self):
        # The test script generated by the inner gentest command.
        self.assertTextFileCorrect(os.path.join(self.cwd, 'testalice1.py'),
                                   os.path.join(self.refdir, 'testalice1.py'),
                                   encoding='ascii')


if __name__ == '__main__':
    ReferenceTestCase.main()
